version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app/
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./server:/app
volumes:
  db-volume:
