version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app/
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
      - "9229:9229"
    volumes:
      - ./server:/app
